
orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.1.1
version: 2.1
jobs:
  deploy:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-region: $AWS_REGION
          from: www.yourmet.de/public
          to: $YOURMET_TARGET
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: www.yourmet.de/
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build

